### ISSUE TITLE
Visual Studio Code - jsconfig.json

### ISSUE THREAD

**Issue by meeximum** [driftyco/ionic-conference-app#102]
Hi,

I'm using Visual Studio Code, do you know if you really need a jsconfig.json file next to the tsconfig.json file?
The error messages complaining ES6 only go away when I create a jsconfig.json as a copy of the tsconfig.json?

I'm working on Windows 10?

regards
Meex

**Comment by 3dd13** [comment]
I am not using Windows and Visual Studio.
but a quick google search suggest that your project is interpreted as javascript application but not typescript application, that's why it still expects the jsconfig.json

reference: 
- https://code.visualstudio.com/docs/languages/javascript
- https://code.visualstudio.com/docs/languages/typescript

**Comment by 3dd13** [comment]
perhaps there is an option to force it treating your project/files as Typescript ?
try look for the "programming language" option in the editor, 

perhaps it is the expected location of the tsconfig.json is different in Visual Studio ? there is an issue reported:
https://github.com/Microsoft/TypeScript/issues/3124

**Comment by meeximum** [comment]
thx for the hints!
