### ISSUE TITLE
Landing page handling according to Login/Signup/Logout is missing

### ISSUE THREAD

**Issue by rajeevkumarsharma** [driftyco/ionic-conference-app#107]
Pls add support to signup.
Show tutorial page only once when application is started first time.
User can see schedule list only after sign-in.
Once user logout, user will be redirected to login page until successful login.
Login session should be maintained.

**Comment by 3dd13** [comment]
1)
add reference to previous discussion with brandyscarney in https://github.com/driftyco/ionic-conference-app/issues/54
"Yes, I agree the user should be able to view the app without viewing the login or signup screen."

2)
submitted a pull request for login status persistence in local storage: https://github.com/driftyco/ionic-conference-app/pull/111

3)
"Show tutorial page only once when application is started first time."
do you want to implement that and submit a pull request ?

perhaps want to discuss with the core team first before making changes ?
that this tutorial pages could be purposely showing everytime, since this conference app is more demonstrating the Ionic features.
not sure their stand on this change.

**Comment by rajeevkumarsharma** [comment]
1)
"No, I am not agree that a user should be able to view the app without viewing the login or signup screen."

2)
User should first signup/Login to see app
Once user logged-in and open app again then only user can see app without re-login for a period of time(cache)

3) 
User can also have some roles so, he should be redirected to role based screens.

**Comment by 3dd13** [comment]
@rajeevkumarsharma
no offense
but it looks like you are dictating the way this app should work like what you personally expect
this repo is more for demonstrating the Ionic framework
and we should come up together what this app should look like so that other Ionic developers can benefit from (and I believe the driftyco organization has the final say with this github repo)

there are many workflows that Ionic framework can implement
perhaps you start a new git repo, and let community contribute as another ionic v2 starter template ?

**Comment by rajeevkumarsharma** [comment]
It's not what i personally expect but what every one expect from an framework to handle authentication workflow

**Comment by brandyscarney** [comment]
Thanks for the feedback. Adding login/logout capabilities is definitely on the roadmap. It is the reason that the login, signup, and account pages aren't checked here, as they are not completed: #54 

Please understand that we are working on building out the SDK at the same time we are updating this app, and any major issues with the SDK itself take priority over adding new features to this demo. If there is a feature you really want added, PR's are welcome, I have merged a few from @3dd13 already.

If you have suggestions for how something should work, please add it to that issue (#54). As @3dd13 stated, there are many workflows that could be implemented, and whichever workflow we decide on won't work for **everyone**. We want to use this app to show off the components of Ionic 2, but it is hard to make everyone happy with the way it works. Thanks again!
