### ISSUE TITLE
Android splashscreen not showing

### ISSUE THREAD

**Issue by jbotuckBH** [driftyco/ionic-conference-app#172]
my system info
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: Windows 7 SP1
Node Version: v4.2.6

**Comment by sghoe** [comment]
Hello jbotuchBH,

I had the same issue in conference-app and my app.
Updating the plugin fixed it for me.

**Comment by jbotuckBH** [comment]
In my app the problem was that the display time and fade time were equal. In order for the screen to show the display time must be > the fade time

**Comment by jgw96** [comment]
Hello @jbotuckBH ! Thanks for opening an issue with us! Are you still having this issue?

**Comment by jbotuckBH** [comment]
yes using

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
OS: Windows 7 SP1
Node Version: v4.2.6

**Comment by jgw96** [comment]
@jbotuckBH Would you mind pulling the latest code (`git pull`) and trying again? This way you will have the latest version which uses ionic 2 beta.6

**Comment by brandyscarney** [comment]
Hey! This should be fixed with the latest code on both the master and typescript branch. Please clone a fresh copy of the conference app, run `npm install` and then `ionic platform add android` (run `ionic platform rm android` if it is already installed). Then, run `ionic run android` and it should be fixed. Note: you may need to remove the conference app from your device if it is already installed. Let me know if you can still reproduce, thanks!
