### ISSUE TITLE
 How i navigate from any TabsPage to TutorialPage??

### ISSUE THREAD

**Issue by uiktiomasfeliz** [driftyco/ionic-conference-app#173]
#### Short description of the problem:
Can't navigate from any TabsPage (SchedulePage,SpeakerListPage,MapPage,AboutPage) to TutorialPage hiding topbar and the tabs

I tried :

```
this.nav.push(TutorialPage);    
```
and
```
this.nav.setRoot(TutorialPage);
```

![bug](https://cloud.githubusercontent.com/assets/5663564/14127077/a830eb0c-f615-11e5-9327-6a80f8b585a1.PNG)

![iosbug](https://cloud.githubusercontent.com/assets/5663564/14127579/545d7b18-f619-11e5-80ee-a8dc5e4aaaca.PNG)

**Which branch are you on?** master or typescript
typescript

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS:
Node Version: v4.3.2

**Comment by brandyscarney** [comment]
Hey! Thanks for the issue. This is actually a support question. In the future can you please post any support questions on the forum under the ionic 2 category: https://forum.ionicframework.com/c/ionic-2

It will help other people who have the same question as you to find an answer there! The reason `nav.push` doesn't work is because the tabs have a separate nav stack. You need to grab the parent `nav` and change it that way, i.e:

```
goToTutorial() {
  let nav = this.app.getComponent('nav');

  nav.setRoot(TutorialPage);
}
```

or

```
goToTutorial() {
  let nav = this.app.getComponent('nav');

  nav.push(TutorialPage);
}
```

:smile:
