### ISSUE TITLE
White screen when run on android 4.3

### ISSUE THREAD

**Issue by mamhf** [driftyco/ionic-conference-app#184]
After the last update when i enter run on android i have a blanc screen
Android version: 4.1
I get this message from Android Device Monitor
![image](https://cloud.githubusercontent.com/assets/10777824/14464704/42d4916c-00d0-11e6-8998-c107859c650a.png)

**Comment by cillay** [comment]
Hi.I tried to help before thinking that bind was undefined, but it looks like the function for which the bind method is being invoked is undefined. I also had something like this before, with a white screen (essentially a fatal JavaScript error before the rendering) and it turned out to be a Google Maps library referencing objects that had not loaded yet.  If you can trace down the error, maybe do some dependent script loads with a DOMContentLoaded event listener. A change in Ionic may be influencing load timings, but this to me does not sound like an Ionic problem. Mu similar issue was not related to Ionic (at that point I was still using 1.0.0-beta.11).

If you can debug with Webkit inspector and get a longer stack trace that might help narrow things down.

**Comment by evgeniynet** [comment]
Hi, same issue

thanks for posting great tool. I am a newby in ionic and I need to run my ionic 2 app on old android devices (2.2) with ecmascript 3 support.
Especially I got errors on "delete" methods which is reserved in es3,
is there is option how to specify target ES3 or use es3ify to have compatibility to older browsers?

Any help appreciated,
Eugene

**Comment by jgw96** [comment]
Hello @mamhf ! Thanks for opening an issue with us! Would you be able to try crosswalk with your app? We recommend using crosswalk on any version of android older than 4.4 as the webview on those older versions of android are really slow and have bad html5 support. Here is a good link on how to use crosswalk with ionic: http://ionicframework.com/docs/cli/browsers.html . @evgeniynet Unfortunately we do not officially support android versions older than 4.2. Also crosswalk only supports android 4.1 and up so im not sure of how this could be solved at the moment. Sorry about that!

**Comment by cillay** [comment]
Here is a table showing just what Angular 2 officially supports:
https://twitter.com/bradlygreen/status/651503849623064576/photo/1

**Comment by evgeniynet** [comment]
thanks

**Comment by evgeniynet** [comment]
please look on https://github.com/driftyco/ionic-cli/issues/898
I fixed this on changing

exports.raf = window.requestAnimationFrame || window.webkitRequestAnimationFrame;

need to change in ionic.js in  node_modules/ionic-angular/bundles
or
app.bundle.js (each build)

**Comment by evgeniynet** [comment]
now runs with success on https://www.manymo.com 4.1 - 4.2 emulators
