### ISSUE TITLE
Remove JS version and make TS master

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-conference-app#191]

**Comment by brandyscarney** [comment]
So the conference app is used by the start command in the CLI here:

https://github.com/driftyco/ionic-app-lib/blob/v2/lib/start.js#L42-L48

and it checks for the typescript branch so we can't remove it until this is handled by the CLI:

https://github.com/driftyco/ionic-app-lib/blob/v2/lib/start.js#L183

making this blocked by: https://github.com/driftyco/ionic-cli/issues/906

**Comment by aarjithn** [comment]
Sorry, but what is the reason to remove es6 branch and make ts master?

**Comment by ghenry22** [comment]
I agree as both es6 and ts are supposed to be fully supported options and first class citizens here should they either:
1) each be kept in a seperate branch
2) each by kept in a seperate repository

One thing I have found perpetually frustrating with ionic2 is searching for how to do something or how to resolve something and then having to work out if people are doing things in ts or es6 and then potentially search again to find why the solution breaks because it was for one or the other.

Having a clear sample app for each option would probably help to save a lot of confusion and googling for new starters with ionic2

**Comment by brandyscarney** [comment]
We've added a document with the reasoning behind this change here: http://ionicframework.com/docs/v2/resources/typescript/

Ionic will still work with ES6, but we are going all in on TypeScript. All starters are now using TypeScript by default and our examples will continue to be in TypeScript. We think this will also clear up the confusion between the ES6 and TS starters.
