### ISSUE TITLE
Profile page crashing when trying to change the name to an empty string

### ISSUE THREAD

**Issue by gfviegas** [driftyco/ionic-conference-app#246]
Hey, if you go to Profile Page and change the name to an empty string the page will never show correctly again. I was looking for validation in a prompt just like in the ionic-conference-app so Im unlucky...

What's the solution to this?

**Comment by GabrielHobold** [comment]
After updating the username to an empty string the page doesn't show correctly because there's a *ngIf="username" in the parent div that hides all the content if the username is not present. 

Looking at the [documentation](http://ionicframework.com/docs/v2/api/components/alert/AlertController/) there's no way to validate the field, unless you use the handler function and do your validations on js.

I recommend creating a form inside a modal as the documentation says "If you require a complex form UI which doesn't fit within the guidelines of an alert then we recommend building the form within a modal instead."

That's not a "complex form" but it's the only way of doing the validations. Maybe the Ionic team adds something in the future.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our [forum](https://forum.ionicframework.com). Thanks for using Ionic!
