### ISSUE TITLE
Android App size is too large, how to decrease?

### ISSUE THREAD

**Issue by ghorimilan** [driftyco/ionic-conference-app#384]
i checkout the code and generate build ,but build size is too large for android

app size  is 
**1. android-armv7-debug.apk ( 29.2 MB )
2. android-x86-debug.apk ( 34.5 MB )**

and **ios size is 7.5** MB

please help any one,
how to decrease the size of app for android?

**Comment by gianpaj** [comment]
this is not the place for this kind of question specific to your use case. also this is not related to this conference app

check https://forum.ionicframework.com

btw you can try to run `ionic build android --prod`

FYI See these `@ionic/app-scripts` commands options:
https://github.com/driftyco/ionic-app-scripts#all-available-tasks

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This is because by default we are using [crosswalk](https://crosswalk-project.org/) to provide good performance on Android < 5.0. Crosswalk is great, but unfortunately it does inflate the size of apk's as it bundles an entire chrome webview with the app. If you are running  Android 5.0 and up you will not need crosswalk as the webview in Android 5.0 and up is just chrome and updates as often as the chrome browser updates.

**Comment by ghorimilan** [comment]
@gianpaj i apologize, i face issue 

@jgw96 thank for your support

i just remove crosswalk plugin from config.xml,size will be 3.5 MB !

```
<plugin name="cordova-plugin-crosswalk-webview" spec="~2.2.0">
    <variable name="XWALK_VERSION" value="22+"/>
    <variable name="XWALK_LITEVERSION" value="xwalk_core_library_canary:17+"/>
    <variable name="XWALK_COMMANDLINE" value="--disable-pull-to-refresh-effect"/>
    <variable name="XWALK_MODE" value="embedded"/>
    <variable name="XWALK_MULTIPLEAPK" value="true"/>
  </plugin>
```

again thanks

**Comment by arnoldparge** [comment]
@jgw96 you said "by default we are using crosswalk". You sure?
Because in my Ionic project I dont have anything related to crosswalk. I had to install crosswalk on my own.

**Comment by lucasbasquerotto** [comment]
@arnoldparge I think he means by default in this project (conference app).
