### ISSUE TITLE
how to add an angular module?

### ISSUE THREAD

**Issue by zebarahman** [driftyco/ionic-conference-app#88]
I am trying to add 'ngCart' module in this app
https://github.com/snapjay/ngCart
but I dont know where to add the directive in this new structure

**Comment by tlancina** [comment]
Good question! ngCart looks like it's an angular 1 directive, so I'm not sure you'll be able to use it unless the author decides to create an angular 2 version.  I'm not super familiar with the angular 1 upgrade process, so it's possible there is a way to convert it easily. You could take a look at https://github.com/angular/ngUpgrade and http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html which go into more detail on the process.

Going to close this as it's not specifically a conference app issue, but if you're having further issues you should consider posting to the forums: https://forum.ionicframework.com/, since there will be more people to help you and it might be helpful to others as well :)
